

debug: false # 디버그 로그 설정 true 로 하면 로그가 너무 길게 나옴
management:
  endpoints:
    web:
      exposure:
        include: "*" # actuator endpoint 모두 가능

logging:
  level:
    com.example.gromit: debug # 디버그 레벨 설정 선택적으로 가능
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # jpa 쿼리 로그를 debug 모드로 관찰 가능 ( bing parameter 를 보여줌 )

spring:
  datasource:
    url: jdbc:mysql://gromit-mysql.comnx9emwbgy.ap-northeast-2.rds.amazonaws.com:3306/gromit
    username: root
    password: gromit123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: false  #테스트용 데이터베이스를 만들 수 있게 해줌 (data.sql)
    hibernate:
      ddl-auto: update # entity class 를 자동으로 create 해서 db 에 만들어줌
    show-sql: true # sql 쿼리문을 보여줌
    properties:
      hibernate:
        format_sql: false #  여러 줄로 나오는 쿼리문을 한 줄로 포맷팅햇 보여줌
        default_batch_fetch_size: 100 # 연관 관계를 가졌을 때 10개의 쿼리문을 id.in 하나로 select 해서 보여줌
  h2:
    console:
      enabled: false # h2
  sql:
    init:
      mode: always # data.sql 실행 설정

  # thymeleaf.cache: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf3:
    decoupled-logic: true

#  data:
#    rest:
#      base-path: /api
server:
  port: 8081
---
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

# [그림 1.8] Team ID 값 입력
APPLE:
  AUTH:
    TOKEN:
      URL: https://appleid.apple.com/auth/token
  PUBLICKEY:
    URL: https://appleid.apple.com/auth/keys
  WEBSITE:
    URL: https://gromit.shop
  ISS: https://applid.apple.com
  AUD: io.gromit.services
  TEAM:
    ID: WCVG52JG6Z
  KEY:
    ID: 28GD5FQ8NV
    PATH: static/apple/AuthKey_28GD5FQ8NV.p8



#
#  datasource:
#    url: jdbc:h2:mem:board:mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none